sequenceDiagram
    Usuario->>+Navegador: Abre la website
    Navegador->>+Servidor: GET /exampleapp/notes
    Servidor->>-Navegador: HTML, CSS, JS
    Usuario->>+Navegador: Escribe una nota
    Usuario->>+Navegador: Hace click en save
    Navegador->>+Servidor: POST /exampleapp/notes/new_note
    Servidor->>-Navegador: HTTP 302 Found (redireccion)
    Navegador->>-Servidor: GET /exampleapp/notes
    Servidor->>+Navegador: HTTP actualizaco con la nueva nota

